### ISSUE TITLE
Quotes can be used to define variable IDs with spaces

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur-cli#222]
GIVEN I have a variable with an ID with a space (ex: `- !variable "foo bar"`)
WHEN I set the variable using the CLI (`conjur variable values add "foo bar" secret123`)
THEN the value of `foo bar` is set to "secret123"

**Comment by dividedmind** [comment]
Ok, so this has actually been fixed by @micahlee in cyberark/conjur-api-ruby#139 in conjur-api-5.2.0 and pulled by @apotterri in 417b9933c5a704dfb26646b04084c7b0373f7f02 -- consequently fix has already been included in version 6.2.0. (The best kind of fix -- already done! ;) ) 

I've verified that indeed it works out of the box with `cyberark/conjur-cli:5`. Would have saved me some time if I didn't start with `conjurinc/cli5` -- I wonder whether it might make sense to tag images under both names.

**Comment by dividedmind** [comment]
@jvanderhoof can you verify and close this? Thanks.

**Comment by jvanderhoof** [comment]
I verified it works as:
```
$ conjur variable values add "staging/myapp/foo\ bar" testing
```
and reached out to Perry about documenting  this convention.
