### ISSUE TITLE
There is a new release of the Conjur CLI

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-cli#298]
Following #297, we need to bump the version and publish a new release of the Conjur CLI so that self-API key rotation can work with Conjur v1.9.0+ and DAP v11.7+.

**Comment by sgnn7** [comment]
#### Per investigation of #1900 by @sashaCher and myself, this issue is no longer valid so it's being closed. 

Details:
-----
- CLI uses both `Conjur::API.rotate_api_key(username, password)` and `api.resource(...).rotate_api_key`
- The first one works and the second does not for rotating your own key due to the change
- When rotating your own (implicit) API key, the CLI uses the first one
- When rotating someone else’s api key (using the `--user` or `--host` flag), the CLI uses the second approach
- The CLI does not allow you to use your own identity when using the `--host` or `--user` flag

Relevant snippets:
- https://github.com/cyberark/conjur-cli/blob/8dad66b483fbe1c8b00e124f47f928677419b87a/lib/conjur/command/hosts.rb#L48-L52
- https://github.com/cyberark/conjur-cli/blob/8dad66b483fbe1c8b00e124f47f928677419b87a/lib/conjur/command/users.rb#L47-L50
